// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Solver.BingRouteService {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="BasicHttpBinding_IRouteService", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    public partial class RouteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalculateRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateRoutesFromMajorRoadsOperationCompleted;
        
        public RouteService() {
            this.Url = "http://dev.virtualearth.net/webservices/v1/routeservice/routeservice.svc";
        }
        
        public RouteService(string url) {
            this.Url = url;
        }
        
        public event CalculateRouteCompletedEventHandler CalculateRouteCompleted;
        
        public event CalculateRoutesFromMajorRoadsCompletedEventHandler CalculateRoutesFromMajorRoadsCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/CalculateRoute", RequestNamespace="http://dev.virtualearth.net/webservices/v1/route/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/route/contracts", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteResponse CalculateRoute([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RouteRequest request) {
            object[] results = this.Invoke("CalculateRoute", new object[] {
                        request});
            return ((RouteResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginCalculateRoute(RouteRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CalculateRoute", new object[] {
                        request}, callback, asyncState);
        }
        
        public RouteResponse EndCalculateRoute(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RouteResponse)(results[0]));
        }
        
        public void CalculateRouteAsync(RouteRequest request) {
            this.CalculateRouteAsync(request, null);
        }
        
        public void CalculateRouteAsync(RouteRequest request, object userState) {
            if ((this.CalculateRouteOperationCompleted == null)) {
                this.CalculateRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateRouteCompleted);
            }
            this.InvokeAsync("CalculateRoute", new object[] {
                        request}, this.CalculateRouteOperationCompleted, userState);
        }
        
        private void OnCalculateRouteCompleted(object arg) {
            if ((this.CalculateRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateRouteCompleted(this, new CalculateRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/CalculateRoutesFromMajorRoads", RequestNamespace="http://dev.virtualearth.net/webservices/v1/route/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/route/contracts", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MajorRoutesResponse CalculateRoutesFromMajorRoads([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MajorRoutesRequest request) {
            object[] results = this.Invoke("CalculateRoutesFromMajorRoads", new object[] {
                        request});
            return ((MajorRoutesResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginCalculateRoutesFromMajorRoads(MajorRoutesRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CalculateRoutesFromMajorRoads", new object[] {
                        request}, callback, asyncState);
        }
        
        public MajorRoutesResponse EndCalculateRoutesFromMajorRoads(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MajorRoutesResponse)(results[0]));
        }
        
        public void CalculateRoutesFromMajorRoadsAsync(MajorRoutesRequest request) {
            this.CalculateRoutesFromMajorRoadsAsync(request, null);
        }
        
        public void CalculateRoutesFromMajorRoadsAsync(MajorRoutesRequest request, object userState) {
            if ((this.CalculateRoutesFromMajorRoadsOperationCompleted == null)) {
                this.CalculateRoutesFromMajorRoadsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateRoutesFromMajorRoadsCompleted);
            }
            this.InvokeAsync("CalculateRoutesFromMajorRoads", new object[] {
                        request}, this.CalculateRoutesFromMajorRoadsOperationCompleted, userState);
        }
        
        private void OnCalculateRoutesFromMajorRoadsCompleted(object arg) {
            if ((this.CalculateRoutesFromMajorRoadsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateRoutesFromMajorRoadsCompleted(this, new CalculateRoutesFromMajorRoadsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteRequest : RequestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteOptions Options;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        public Waypoint[] Waypoints;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MajorRoutesOptions))]
    public partial class RouteOptions {
        
        /// <remarks/>
        public TravelMode Mode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool ModeSpecified;
        
        /// <remarks/>
        public RouteOptimization Optimization;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OptimizationSpecified;
        
        /// <remarks/>
        public RoutePathType RoutePathType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool RoutePathTypeSpecified;
        
        /// <remarks/>
        public TrafficUsage TrafficUsage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TrafficUsageSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum TravelMode {
        
        /// <remarks/>
        Driving,
        
        /// <remarks/>
        Walking,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum RouteOptimization {
        
        /// <remarks/>
        MinimizeTime,
        
        /// <remarks/>
        MinimizeDistance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum RoutePathType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Points,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum TrafficUsage {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        TrafficBasedTime,
        
        /// <remarks/>
        TrafficBasedRouteAndTime,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesOptions : RouteOptions {
        
        /// <remarks/>
        public bool ReturnRoutes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool ReturnRoutesSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class Waypoint {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeocodeLocation))]
    public partial class Location {
        
        /// <remarks/>
        public double Altitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool AltitudeSpecified;
        
        /// <remarks/>
        public double Latitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool LatitudeSpecified;
        
        /// <remarks/>
        public double Longitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool LongitudeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserLocation : Location {
        
        /// <remarks/>
        public Confidence Confidence;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool ConfidenceSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum Confidence {
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeLocation : Location {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CalculationMethod;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RouteRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MajorRoutesRequest))]
    public partial class RequestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Credentials Credentials;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Culture;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExecutionOptions ExecutionOptions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserProfile UserProfile;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Credentials {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Token;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ExecutionOptions {
        
        /// <remarks/>
        public bool SuppressFaults;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool SuppressFaultsSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserProfile {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Heading CurrentHeading;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserLocation CurrentLocation;
        
        /// <remarks/>
        public DeviceType DeviceType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool DeviceTypeSpecified;
        
        /// <remarks/>
        public DistanceUnit DistanceUnit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool DistanceUnitSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPAddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ShapeBase MapView;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SizeOfint ScreenSize;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Heading {
        
        /// <remarks/>
        public double Orientation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OrientationSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DeviceType {
        
        /// <remarks/>
        Desktop,
        
        /// <remarks/>
        Mobile,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DistanceUnit {
        
        /// <remarks/>
        Kilometer,
        
        /// <remarks/>
        Mile,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rectangle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Circle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polygon))]
    public partial class ShapeBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Rectangle : ShapeBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Northeast;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Southwest;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Circle : ShapeBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Center;
        
        /// <remarks/>
        public DistanceUnit DistanceUnit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool DistanceUnitSpecified;
        
        /// <remarks/>
        public double Radius;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool RadiusSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Polygon : ShapeBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        public Location[] Vertices;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class SizeOfint {
        
        /// <remarks/>
        public int Height;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool HeightSpecified;
        
        /// <remarks/>
        public int Width;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool WidthSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesRequest : RequestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Waypoint Destination;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MajorRoutesOptions Options;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteResponse : ResponseBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteResult Result;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteResult {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        public RouteLeg[] Legs;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RoutePath RoutePath;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteSummary Summary;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteLeg {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location ActualEnd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location ActualStart;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        public ItineraryItem[] Itinerary;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteSummary Summary;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompassDirection;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        public ItineraryItemHint[] Hints;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location;
        
        /// <remarks/>
        public ManeuverType ManeuverType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool ManeuverTypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteSummary Summary;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        public ItineraryItemWarning[] Warnings;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItemHint {
        
        /// <remarks/>
        public ItineraryItemHintType HintType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool HintTypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryItemHintType {
        
        /// <remarks/>
        PreviousIntersection,
        
        /// <remarks/>
        NextIntersection,
        
        /// <remarks/>
        Landmark,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ManeuverType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        DepartStart,
        
        /// <remarks/>
        DepartIntermediateStop,
        
        /// <remarks/>
        DepartIntermediateStopReturning,
        
        /// <remarks/>
        ArriveFinish,
        
        /// <remarks/>
        ArriveIntermediateStop,
        
        /// <remarks/>
        TurnLeft,
        
        /// <remarks/>
        TurnRight,
        
        /// <remarks/>
        TurnBack,
        
        /// <remarks/>
        UTurn,
        
        /// <remarks/>
        TurnToStayLeft,
        
        /// <remarks/>
        TurnToStayRight,
        
        /// <remarks/>
        BearLeft,
        
        /// <remarks/>
        BearRight,
        
        /// <remarks/>
        KeepToStayLeft,
        
        /// <remarks/>
        KeepToStayRight,
        
        /// <remarks/>
        KeepToStayStraight,
        
        /// <remarks/>
        KeepLeft,
        
        /// <remarks/>
        KeepRight,
        
        /// <remarks/>
        KeepStraight,
        
        /// <remarks/>
        Take,
        
        /// <remarks/>
        TakeRampLeft,
        
        /// <remarks/>
        TakeRampRight,
        
        /// <remarks/>
        TakeRampStraight,
        
        /// <remarks/>
        KeepOnrampLeft,
        
        /// <remarks/>
        KeepOnrampRight,
        
        /// <remarks/>
        KeepOnrampStraight,
        
        /// <remarks/>
        Merge,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        RoadNameChange,
        
        /// <remarks/>
        EnterRoundabout,
        
        /// <remarks/>
        ExitRoundabout,
        
        /// <remarks/>
        TurnRightThenTurnRight,
        
        /// <remarks/>
        TurnRightThenTurnLeft,
        
        /// <remarks/>
        TurnRightThenBearRight,
        
        /// <remarks/>
        TurnRightThenBearLeft,
        
        /// <remarks/>
        TurnLeftThenTurnLeft,
        
        /// <remarks/>
        TurnLeftThenTurnRight,
        
        /// <remarks/>
        TurnLeftThenBearLeft,
        
        /// <remarks/>
        TurnLeftThenBearRight,
        
        /// <remarks/>
        BearRightThenTurnRight,
        
        /// <remarks/>
        BearRightThenTurnLeft,
        
        /// <remarks/>
        BearRightThenBearRight,
        
        /// <remarks/>
        BearRightThenBearLeft,
        
        /// <remarks/>
        BearLeftThenTurnLeft,
        
        /// <remarks/>
        BearLeftThenTurnRight,
        
        /// <remarks/>
        BearLeftThenBearRight,
        
        /// <remarks/>
        BearLeftThenBearLeft,
        
        /// <remarks/>
        RampThenHighwayRight,
        
        /// <remarks/>
        RampThenHighwayLeft,
        
        /// <remarks/>
        RampToHighwayStraight,
        
        /// <remarks/>
        EnterThenExitRoundabout,
        
        /// <remarks/>
        BearThenMerge,
        
        /// <remarks/>
        TurnThenMerge,
        
        /// <remarks/>
        BearThenKeep,
        
        /// <remarks/>
        Transfer,
        
        /// <remarks/>
        Wait,
        
        /// <remarks/>
        TakeTransit,
        
        /// <remarks/>
        Walk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteSummary {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rectangle BoundingRectangle;
        
        /// <remarks/>
        public double Distance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool DistanceSpecified;
        
        /// <remarks/>
        public long TimeInSeconds;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TimeInSecondsSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItemWarning {
        
        /// <remarks/>
        public ItineraryWarningSeverity Severity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool SeveritySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text;
        
        /// <remarks/>
        public ItineraryWarningType WarningType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool WarningTypeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryWarningSeverity {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        LowImpact,
        
        /// <remarks/>
        Minor,
        
        /// <remarks/>
        Moderate,
        
        /// <remarks/>
        Serious,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryWarningType {
        
        /// <remarks/>
        Accident,
        
        /// <remarks/>
        AdminDivisionChange,
        
        /// <remarks/>
        BlockedRoad,
        
        /// <remarks/>
        CheckTimetable,
        
        /// <remarks/>
        Congestion,
        
        /// <remarks/>
        CountryChange,
        
        /// <remarks/>
        DisabledVehicle,
        
        /// <remarks/>
        GateAccess,
        
        /// <remarks/>
        GetOffTransit,
        
        /// <remarks/>
        GetOnTransit,
        
        /// <remarks/>
        IllegalUTurn,
        
        /// <remarks/>
        MassTransit,
        
        /// <remarks/>
        Miscellaneous,
        
        /// <remarks/>
        NoIncident,
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        OtherNews,
        
        /// <remarks/>
        OtherTrafficIncidents,
        
        /// <remarks/>
        PlannedEvent,
        
        /// <remarks/>
        PrivateRoad,
        
        /// <remarks/>
        RestrictedTurn,
        
        /// <remarks/>
        RoadClosures,
        
        /// <remarks/>
        RoadHazard,
        
        /// <remarks/>
        ScheduledConstruction,
        
        /// <remarks/>
        SeasonalClosures,
        
        /// <remarks/>
        Tollbooth,
        
        /// <remarks/>
        TollRoad,
        
        /// <remarks/>
        TrafficFlow,
        
        /// <remarks/>
        UnpavedRoad,
        
        /// <remarks/>
        UnscheduledConstruction,
        
        /// <remarks/>
        Weather,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RoutePath {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        public Location[] Points;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RouteResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MajorRoutesResponse))]
    public partial class ResponseBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="anyURI")]
        public string BrandLogoUri;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseSummary ResponseSummary;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseSummary {
        
        /// <remarks/>
        public AuthenticationResultCode AuthenticationResultCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool AuthenticationResultCodeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Copyright;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FaultReason;
        
        /// <remarks/>
        public ResponseStatusCode StatusCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool StatusCodeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TraceId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum AuthenticationResultCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        NoCredentials,
        
        /// <remarks/>
        ValidCredentials,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        CredentialsExpired,
        
        /// <remarks/>
        NotAuthorized,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum ResponseStatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        ServerError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesResponse : ResponseBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        public RouteResult[] Routes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        public Waypoint[] StartingPoints;
    }
    
    public partial class CalculateRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RouteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void CalculateRouteCompletedEventHandler(object sender, CalculateRouteCompletedEventArgs args);
    
    public partial class CalculateRoutesFromMajorRoadsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateRoutesFromMajorRoadsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MajorRoutesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MajorRoutesResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void CalculateRoutesFromMajorRoadsCompletedEventHandler(object sender, CalculateRoutesFromMajorRoadsCompletedEventArgs args);
}
